steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: './build/deployable'
    args:
      - functions
      - deploy
      - kickOffPipeline
      - --trigger-bucket=inbound-feed-bucket
      - --runtime
      - node10
      - --set-env-vars
      - OUTPUT_BUCKET=sandpit-processed-files,TEMPLATE_BUCKET=sandpit-data-flows,PROFILE=$BRANCH_NAME